// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
void ui_event_mainScreen( lv_event_t * e);
lv_obj_t *ui_mainScreen;
lv_obj_t *ui_Logo;
void ui_event_returnButton13( lv_event_t * e);
lv_obj_t *ui_returnButton13;
lv_obj_t *ui_inletMainsScreen;
lv_obj_t *ui_outletMainScreen;
lv_obj_t *ui_highTempAlarmMainScreen;
lv_obj_t *ui_highPressureAlarmMainScreen;
// CUSTOM VARIABLES
lv_obj_t *uic_mainScreen;
lv_obj_t *uic_Logo;
lv_obj_t *uic_returnButton1;
lv_obj_t *uic_inletMainsScreen;
lv_obj_t *uic_outletMainScreen;
lv_obj_t *uic_highTempAlarmMainScreen;
lv_obj_t *uic_highPressureAlarmMainScreen;


// SCREEN: ui_controlSettingScreen
void ui_controlSettingScreen_screen_init(void);
void ui_event_controlSettingScreen( lv_event_t * e);
lv_obj_t *ui_controlSettingScreen;
void ui_event_returnButton4( lv_event_t * e);
lv_obj_t *ui_returnButton4;
lv_obj_t *ui_settingscreenlabel;
void ui_event_SettingCTRL( lv_event_t * e);
lv_obj_t *ui_SettingCTRL;
void ui_event_Advanced_Setting_Button( lv_event_t * e);
lv_obj_t *ui_Advanced_Setting_Button;
void ui_event_TurnOffCTRL( lv_event_t * e);
lv_obj_t *ui_TurnOffCTRL;
void ui_event_Status_info_Button( lv_event_t * e);
lv_obj_t *ui_Status_info_Button;
lv_obj_t *ui_COOLER_IS__ON;
lv_obj_t *ui_COOLER_IS__OFF;
// CUSTOM VARIABLES
lv_obj_t *uic_controlSettingScreen;
lv_obj_t *uic_returnButton4;
lv_obj_t *uic_settingscreenlabel;
lv_obj_t *uic_SettingCTRL;
lv_obj_t *uic_Advanced_Setting_Button;
lv_obj_t *uic_TurnOffCTRL;
lv_obj_t *uic_Status_info_Button;
lv_obj_t *uic_COOLER_IS__ON;
lv_obj_t *uic_COOLER_IS__OFF;


// SCREEN: ui_processSettingScreen
void ui_processSettingScreen_screen_init(void);
void ui_event_processSettingScreen( lv_event_t * e);
lv_obj_t *ui_processSettingScreen;
void ui_event_returnButton5( lv_event_t * e);
lv_obj_t *ui_returnButton5;
lv_obj_t *ui_ProcessSettingCTRL;
void ui_event_Setting_Save_btn( lv_event_t * e);
lv_obj_t *ui_Setting_Save_btn;
lv_obj_t *ui_Setting_Save_btn_label;
lv_obj_t *ui_ProcessScreenContainer1;
lv_obj_t *ui_Compressor_Range_Spinbox;
void ui_event_Compressor_Range_Plus_Button( lv_event_t * e);
lv_obj_t *ui_Compressor_Range_Plus_Button;
void ui_event_Compressor_Range_Minus_Button( lv_event_t * e);
lv_obj_t *ui_Compressor_Range_Minus_Button;
lv_obj_t *ui_Celciuslable1;
lv_obj_t *ui_ProcessScreenContainer2;
lv_obj_t *ui_Compressor_Offste_Spinbox;
void ui_event_Compressor_Offset_Plus_Button( lv_event_t * e);
lv_obj_t *ui_Compressor_Offset_Plus_Button;
void ui_event_Compressor_Offset_Minus_Button( lv_event_t * e);
lv_obj_t *ui_Compressor_Offset_Minus_Button;
lv_obj_t *ui_Celciuslable2;
lv_obj_t *ui_ProcessScreenContainer3;
lv_obj_t *ui_High_Temp_Alarm_Spinbox;
void ui_event_High_Temp_Alarm_Plus_Button( lv_event_t * e);
lv_obj_t *ui_High_Temp_Alarm_Plus_Button;
void ui_event_High_Temp_Alarm_Minus_Button( lv_event_t * e);
lv_obj_t *ui_High_Temp_Alarm_Minus_Button;
lv_obj_t *ui_Celciuslable3;
lv_obj_t *ui_ProcessScreenContainer4;
void ui_event_PressureAlarmSwitch( lv_event_t * e);
lv_obj_t *ui_PressureAlarmSwitch;
lv_obj_t *ui_PressureAlarmSwitch_ONlabel;
lv_obj_t *ui_PressureAlarmSwitch_OFFlabel;
lv_obj_t *ui_ProcessScreenContainer5;
void ui_event_TempAlarmSwitch( lv_event_t * e);
lv_obj_t *ui_TempAlarmSwitch;
lv_obj_t *ui_TempAlarmSwitch_ONlabel;
lv_obj_t *ui_TempAlarmSwitch_OFFlabel;
lv_obj_t *ui_High_Temp_Alarm_Label;
lv_obj_t *ui_High_Pressure_Alarm_Label;
lv_obj_t *ui_Compressor_Offset_Label;
lv_obj_t *ui_Compressor_Range_Label;
lv_obj_t *ui_High_Temp_Alarm_Switch_Label;
// CUSTOM VARIABLES
lv_obj_t *uic_processSettingScreen;
lv_obj_t *uic_returnButton5;
lv_obj_t *uic_ProcessSettingCTRL;
lv_obj_t *uic_Setting_Save_btn;
lv_obj_t *uic_Setting_Save_btn_label;
lv_obj_t *uic_ProcessScreenContainer1;
lv_obj_t *uic_Compressor_Range_Spinbox;
lv_obj_t *uic_Compressor_Range_Plus_Button;
lv_obj_t *uic_Compressor_Range_Minus_Button;
lv_obj_t *uic_Celciuslable1;
lv_obj_t *uic_ProcessScreenContainer2;
lv_obj_t *uic_Compressor_Offste_Spinbox;
lv_obj_t *uic_Compressor_Offset_Plus_Button;
lv_obj_t *uic_Compressor_Offset_Minus_Button;
lv_obj_t *uic_Celciuslable2;
lv_obj_t *uic_ProcessScreenContainer3;
lv_obj_t *uic_High_Temp_Alarm_Spinbox;
lv_obj_t *uic_High_Temp_Alarm_Plus_Button;
lv_obj_t *uic_High_Temp_Alarm_Minus_Button;
lv_obj_t *uic_Celciuslable3;
lv_obj_t *uic_ProcessScreenContainer4;
lv_obj_t *uic_PressureAlarmSwitch;
lv_obj_t *uic_PressureAlarmSwitch_ONlabel;
lv_obj_t *uic_PressureAlarmSwitch_OFFlabel;
lv_obj_t *uic_ProcessScreenContainer5;
lv_obj_t *uic_TempAlarmSwitch;
lv_obj_t *uic_TempAlarmSwitch_ONlabel;
lv_obj_t *uic_TempAlarmSwitch_OFFlabel;
lv_obj_t *uic_High_Temp_Alarm_Label;
lv_obj_t *uic_High_Pressure_Alarm_Label;
lv_obj_t *uic_Compressor_Offset_Label;
lv_obj_t *uic_Compressor_Range_Label;
lv_obj_t *uic_High_Temp_Alarm_Label;


// SCREEN: ui_addvansedSettingScreen
void ui_addvansedSettingScreen_screen_init(void);
void ui_event_addvansedSettingScreen( lv_event_t * e);
lv_obj_t *ui_addvansedSettingScreen;
void ui_event_returnButton14( lv_event_t * e);
lv_obj_t *ui_returnButton14;
lv_obj_t *ui_Advanced_Setting_Label;
void ui_event_Setting_Save_btn_in_advanced_Screen( lv_event_t * e);
lv_obj_t *ui_Setting_Save_btn_in_advanced_Screen;
lv_obj_t *ui_Setting_Save_btn_label_advanced_Screen;
lv_obj_t *ui_TabView1;
lv_obj_t *ui_tab1;
lv_obj_t *ui_AdvancedScreenContainer1;
lv_obj_t *ui_AntiFreeze_Temp_Range_Spinbox;
void ui_event_AntiFreeze_Temp_Range_Plus_Button( lv_event_t * e);
lv_obj_t *ui_AntiFreeze_Temp_Range_Plus_Button;
void ui_event_AntiFreeze_Temp_Range_Minus_Button( lv_event_t * e);
lv_obj_t *ui_AntiFreeze_Temp_Range_Minus_Button;
lv_obj_t *ui_Celciuslabel4;
lv_obj_t *ui_AdvancedScreenContainer2;
lv_obj_t *ui_AntiFreeze_Temp_Offset_Spinbox;
void ui_event_AntiFreeze_Temp_Offset_Plus_Button( lv_event_t * e);
lv_obj_t *ui_AntiFreeze_Temp_Offset_Plus_Button;
void ui_event_AntiFreeze_Temp_Offset_Minus_Button( lv_event_t * e);
lv_obj_t *ui_AntiFreeze_Temp_Offset_Minus_Button;
lv_obj_t *ui_Celciuslable5;
lv_obj_t *ui_AdvancedScreenContainer3;
lv_obj_t *ui_Compressor_Rest_Time_Spinbox;
void ui_event_Compressor_Rest_Time_Plus_Button( lv_event_t * e);
lv_obj_t *ui_Compressor_Rest_Time_Plus_Button;
void ui_event_Compressor_Rest_Time_Minus_Button( lv_event_t * e);
lv_obj_t *ui_Compressor_Rest_Time_Minus_Button;
lv_obj_t *ui_minutelable11;
lv_obj_t *ui_AdvancedScreenContainer4;
lv_obj_t *ui_Filter_Alarm_Spinbox;
void ui_event_Filter_Alarm_Plus_Button( lv_event_t * e);
lv_obj_t *ui_Filter_Alarm_Plus_Button;
void ui_event_Filter_Alarm_Minus_Button( lv_event_t * e);
lv_obj_t *ui_Filter_Alarm_Minus_Button;
lv_obj_t *ui_Celciuslable6;
lv_obj_t *ui_Compressor_Rest_Time_Label;
lv_obj_t *ui_AntiFreeze_Temp_Offset_Label;
lv_obj_t *ui_AntiFreeze_Temp_Range_Label;
lv_obj_t *ui_Filter_Alarm__Range_Label;
lv_obj_t *ui_tab2;
lv_obj_t *ui_AdvancedScreenContainer5;
lv_obj_t *ui_fan_2_range_Spinbox;
void ui_event_fan_2_range_Plus_Button( lv_event_t * e);
lv_obj_t *ui_fan_2_range_Plus_Button;
void ui_event_fan_2_range_Minus_Button( lv_event_t * e);
lv_obj_t *ui_fan_2_range_Minus_Button;
void ui_event_fan_2_Switch( lv_event_t * e);
lv_obj_t *ui_fan_2_Switch;
lv_obj_t *ui_enable_fan_2_Label;
lv_obj_t *ui_disable_fan_2_Label;
lv_obj_t *ui_fan_2_range_Label;
lv_obj_t *ui_AdvancedScreenContainer6;
void ui_event_door_alarm_status_Switch( lv_event_t * e);
lv_obj_t *ui_door_alarm_status_Switch;
lv_obj_t *ui_enable_door_alarm_status_Label;
lv_obj_t *ui_disable_door_alarm_status_Label;
lv_obj_t *ui_door_function_and_alarm_Label;
lv_obj_t *ui_AdvancedScreenContainer7;
void ui_event_filter_alarm_status_Switch( lv_event_t * e);
lv_obj_t *ui_filter_alarm_status_Switch;
lv_obj_t *ui_enable_filter_alarm_status_Label;
lv_obj_t *ui_disable_filter_alarm_status_Label;
lv_obj_t *ui_Filter_alarm_switch_Label;
lv_obj_t *ui_tab3;
lv_obj_t *ui_Label456;
void ui_event_Sensor_Setup_Button( lv_event_t * e);
lv_obj_t *ui_Sensor_Setup_Button;
lv_obj_t *ui_Sensor_Setup_Button_Label;
lv_obj_t *ui_Label123;
void ui_event_open_factory_reset_panel( lv_event_t * e);
lv_obj_t *ui_open_factory_reset_panel;
lv_obj_t *ui_factory_reset_btn_Label;
lv_obj_t *ui_sensors_setup_container;
void ui_event_close_sensor_setup_container_Button( lv_event_t * e);
lv_obj_t *ui_close_sensor_setup_container_Button;
void ui_event_search_sensor_setup_Button( lv_event_t * e);
lv_obj_t *ui_search_sensor_setup_Button;
lv_obj_t *ui_search_sensor_setup_Button_Label;
lv_obj_t *ui_setup_sensors_Label;
lv_obj_t *ui_inlet_Panel;
void ui_event_inlet_Checkbox( lv_event_t * e);
lv_obj_t *ui_inlet_Checkbox;
lv_obj_t *ui_inlet_address;
lv_obj_t *ui_outlet_Panel;
void ui_event_outlet_Checkbox( lv_event_t * e);
lv_obj_t *ui_outlet_Checkbox;
lv_obj_t *ui_outlet_address;
lv_obj_t *ui_filter_Panel;
void ui_event_filter_Checkbox( lv_event_t * e);
lv_obj_t *ui_filter_Checkbox;
lv_obj_t *ui_filter_address;
lv_obj_t *ui_antifreeze_Panel;
void ui_event_antifreeze_Checkbox( lv_event_t * e);
lv_obj_t *ui_antifreeze_Checkbox;
lv_obj_t *ui_antifreeze_address;
lv_obj_t *ui_factory_reset_container;
lv_obj_t *ui_reset_factory_notice_text;
void ui_event_close_factory_container( lv_event_t * e);
lv_obj_t *ui_close_factory_container;
lv_obj_t *ui_Label275;
void ui_event_submit_factory_( lv_event_t * e);
lv_obj_t *ui_submit_factory_;
lv_obj_t *ui_Label1863;
// CUSTOM VARIABLES
lv_obj_t *uic_addvansedSettingScreen;
lv_obj_t *uic_returnButton14;
lv_obj_t *uic_Advanced_Setting_Label;
lv_obj_t *uic_Setting_Save_btn_in_advanced_Screen;
lv_obj_t *uic_Setting_Save_btn_label_advanced_Screen;
lv_obj_t *uic_AdvancedScreenContainer1;
lv_obj_t *uic_AntiFreeze_Temp_Range_Spinbox;
lv_obj_t *uic_AntiFreeze_Temp_Range_Plus_Button;
lv_obj_t *uic_AntiFreeze_Temp_Range_Minus_Button;
lv_obj_t *uic_Celciuslabel4;
lv_obj_t *uic_AdvancedScreenContainer2;
lv_obj_t *uic_AntiFreeze_Temp_Offset_Spinbox;
lv_obj_t *uic_AntiFreeze_Temp_Offset_Plus_Button;
lv_obj_t *uic_AntiFreeze_Temp_Offset_Minus_Button;
lv_obj_t *uic_Celciuslable5;
lv_obj_t *uic_AdvancedScreenContainer3;
lv_obj_t *uic_Compressor_Rest_Time_Spinbox;
lv_obj_t *uic_Compressor_Rest_Time_Plus_Button;
lv_obj_t *uic_Compressor_Rest_Time_Minus_Button;
lv_obj_t *uic_minutelable11;
lv_obj_t *uic_AdvancedScreenContainer4;
lv_obj_t *uic_Filter_Alarm_Spinbox;
lv_obj_t *uic_Filter_Alarm_Plus_Button;
lv_obj_t *uic_Filter_Alarm_Minus_Button;
lv_obj_t *uic_Celciuslable6;
lv_obj_t *uic_Compressor_Rest_Time_Label;
lv_obj_t *uic_AntiFreeze_Temp_Offset_Label;
lv_obj_t *uic_AntiFreeze_Temp_Range_Label;
lv_obj_t *uic_Filter_Alarm__Range_Label;
lv_obj_t *uic_AdvancedScreenContainer5;
lv_obj_t *uic_fan_2_range_Spinbox;
lv_obj_t *uic_fan_2_range_Plus_Button;
lv_obj_t *uic_fan_2_range_Minus_Button;
lv_obj_t *uic_fan_2_Switch;
lv_obj_t *uic_enable_fan_2_Label;
lv_obj_t *uic_disable_fan_2_Label;
lv_obj_t *uic_fan_2_range_Label;
lv_obj_t *uic_AdvancedScreenContainer6;
lv_obj_t *uic_door_alarm_status_Switch;
lv_obj_t *uic_enable_door_alarm_status_Label;
lv_obj_t *uic_disable_door_alarm_status_Label;
lv_obj_t *uic_door_function_and_alarm_Label;
lv_obj_t *uic_AdvancedScreenContainer7;
lv_obj_t *uic_filter_alarm_status_Switch;
lv_obj_t *uic_enable_filter_alarm_status_Label;
lv_obj_t *uic_disable_filter_alarm_status_Label;
lv_obj_t *uic_Filter_alarm_switch_Label;
lv_obj_t *uic_Label456;
lv_obj_t *uic_Sensor_Setup_Button;
lv_obj_t *uic_Sensor_Setup_Button_Label;
lv_obj_t *uic_Label123;
lv_obj_t *uic_open_factory_reset_panel;
lv_obj_t *uic_factory_reset_btn_Label;
lv_obj_t *uic_sensors_setup_container;
lv_obj_t *uic_close_sensor_setup_container_Button;
lv_obj_t *uic_search_sensor_setup_Button;
lv_obj_t *uic_setup_sensors_Label;
lv_obj_t *uic_inlet_Panel;
lv_obj_t *uic_inlet_Checkbox;
lv_obj_t *uic_inlet_address;
lv_obj_t *uic_outlet_Panel;
lv_obj_t *uic_outlet_Checkbox;
lv_obj_t *uic_outlet_address;
lv_obj_t *uic_filter_Panel;
lv_obj_t *uic_filter_Checkbox;
lv_obj_t *uic_filter_address;
lv_obj_t *uic_antifreeze_Panel;
lv_obj_t *uic_antifreeze_Checkbox;
lv_obj_t *uic_antifreeze_address;
lv_obj_t *uic_factory_reset_container;
lv_obj_t *uic_reset_factory_notice_text;
lv_obj_t *uic_Label275;
lv_obj_t *uic_submit_factory_;
lv_obj_t *uic_Label1863;


// SCREEN: ui_statusScreen
void ui_statusScreen_screen_init(void);
void ui_event_statusScreen( lv_event_t * e);
lv_obj_t *ui_statusScreen;
void ui_event_returnButton3( lv_event_t * e);
lv_obj_t *ui_returnButton3;
lv_obj_t *ui_statusscreenlabel;
lv_obj_t *ui_TEMP_Label;
lv_obj_t *ui_ALARM_Label;
lv_obj_t *ui_Status_Label;
lv_obj_t *ui_Connection_Label;
lv_obj_t *ui_info_Label;
lv_obj_t *ui_Maintenance_Label;
void ui_event_tempStatusButton( lv_event_t * e);
lv_obj_t *ui_tempStatusButton;
lv_obj_t *ui_tempStatusPanel;
void ui_event_returnButton11( lv_event_t * e);
lv_obj_t *ui_returnButton11;
lv_obj_t *ui_tempStatusLabel;
lv_obj_t *ui_ContainerA1;
lv_obj_t *ui_Inlet_Temp_status;
lv_obj_t *ui_Outlet_Temp_status;
lv_obj_t *ui_antifreeze_temp_status;
lv_obj_t *ui_fan_2_filter_alarm_status;
void ui_event_alarmStatusButton( lv_event_t * e);
lv_obj_t *ui_alarmStatusButton;
lv_obj_t *ui_alarmStatusPanel;
void ui_event_returnButton2( lv_event_t * e);
lv_obj_t *ui_returnButton2;
lv_obj_t *ui_alarmStatusLabel;
lv_obj_t *ui_ContainerA2;
lv_obj_t *ui_high_Temp_Alarm;
lv_obj_t *ui_Door_Alarm;
lv_obj_t *ui_Filter_Alarm;
lv_obj_t *ui_high_Pressure_Alarm;
void ui_event_relayStatusButton( lv_event_t * e);
lv_obj_t *ui_relayStatusButton;
lv_obj_t *ui_relayStatusPanel;
void ui_event_returnButton7( lv_event_t * e);
lv_obj_t *ui_returnButton7;
lv_obj_t *ui_relayStatusLabel;
lv_obj_t *ui_ContainerA3;
lv_obj_t *ui_evaprartor_Fan_Status;
lv_obj_t *ui_Compressor_Status;
lv_obj_t *ui_condensor_Fan_1_Status;
lv_obj_t *ui_condensor_Fan_2_Status;
void ui_event_networkStatusButton( lv_event_t * e);
lv_obj_t *ui_networkStatusButton;
lv_obj_t *ui_networkStatusPanel;
void ui_event_returnButton8( lv_event_t * e);
lv_obj_t *ui_returnButton8;
lv_obj_t *ui_Connect_to_Device_Label;
lv_obj_t *ui_ContainerA4;
lv_obj_t *ui_access_Point_wifi;
lv_obj_t *ui_access_Point_Password;
lv_obj_t *ui_guidetext;
lv_obj_t *ui_QRcode_Tab;
lv_obj_t *ui_appldownload;
lv_obj_t *ui_Application_QR_Code;
lv_obj_t *ui_download_App_Label;
lv_obj_t *ui_connectToapp;
lv_obj_t *ui_Connection_QR_Code;
lv_obj_t *ui_Connect_App_Label;
void ui_event_show_QR_Code_Button( lv_event_t * e);
lv_obj_t *ui_show_QR_Code_Button;
void ui_event_Hide_QR_Code_Button( lv_event_t * e);
lv_obj_t *ui_Hide_QR_Code_Button;
void ui_event_deviceInfoButton( lv_event_t * e);
lv_obj_t *ui_deviceInfoButton;
lv_obj_t *ui_deviceInfoPanel;
void ui_event_returnButton9( lv_event_t * e);
lv_obj_t *ui_returnButton9;
lv_obj_t *ui_deviceInfoLabel;
lv_obj_t *ui_ContainerA5;
lv_obj_t *ui_serial_number;
lv_obj_t *ui_customerID;
lv_obj_t *ui_activationDate;
void ui_event_serviceInfoButton( lv_event_t * e);
lv_obj_t *ui_serviceInfoButton;
lv_obj_t *ui_serviceInfoPanel;
void ui_event_returnButton10( lv_event_t * e);
lv_obj_t *ui_returnButton10;
lv_obj_t *ui_serviceInfoLabel;
lv_obj_t *ui_ContainerA6;
lv_obj_t *ui_servicesintervals;
// CUSTOM VARIABLES
lv_obj_t *uic_statusScreen;
lv_obj_t *uic_returnButton3;
lv_obj_t *uic_statusscreenlabel;
lv_obj_t *uic_TEMP_Label;
lv_obj_t *uic_ALARM_Label;
lv_obj_t *uic_Status_Label;
lv_obj_t *uic_TEMP_Label;
lv_obj_t *uic_info_Label;
lv_obj_t *uic_Maintenance_Label;
lv_obj_t *uic_tempStatusButton;
lv_obj_t *uic_tempStatusPanel;
lv_obj_t *uic_returnButton11;
lv_obj_t *uic_tempStatusLabel;
lv_obj_t *uic_ContainerA1;
lv_obj_t *uic_Inlet_Temp_status;
lv_obj_t *uic_Outlet_Temp_status;
lv_obj_t *uic_antifreeze_temp_status;
lv_obj_t *uic_fan_2_filter_alarm_status;
lv_obj_t *uic_alarmStatusButton;
lv_obj_t *uic_alarmStatusPanel;
lv_obj_t *uic_returnButton2;
lv_obj_t *uic_alarmStatusLabel;
lv_obj_t *uic_ContainerA2;
lv_obj_t *uic_high_Temp_Alarm;
lv_obj_t *uic_Door_Alarm;
lv_obj_t *uic_Filter_Alarm;
lv_obj_t *uic_high_Pressure_Alarm;
lv_obj_t *uic_relayStatusButton;
lv_obj_t *uic_relayStatusPanel;
lv_obj_t *uic_returnButton7;
lv_obj_t *uic_relayStatusLabel;
lv_obj_t *uic_ContainerA3;
lv_obj_t *uic_evaprartor_Fan_Status;
lv_obj_t *uic_Compressor_Status;
lv_obj_t *uic_condensor_Fan_1_Status;
lv_obj_t *uic_condensor_Fan_2_Status;
lv_obj_t *uic_networkStatusPanel;
lv_obj_t *uic_returnButton8;
lv_obj_t *uic_Connect_to_Device_Label;
lv_obj_t *uic_ContainerA4;
lv_obj_t *uic_access_Point_wifi;
lv_obj_t *uic_access_Point_Password;
lv_obj_t *uic_guidetext;
lv_obj_t *uic_QRcode_Tab;
lv_obj_t *uic_Application_QR_Code;
lv_obj_t *uic_download_App_Label;
lv_obj_t *uic_connectToapp;
lv_obj_t *uic_Connection_QR_Code;
lv_obj_t *uic_Connect_App_Label;
lv_obj_t *uic_show_QR_Code_Button;
lv_obj_t *uic_Hide_QR_Code_Button;
lv_obj_t *uic_deviceInfoPanel;
lv_obj_t *uic_returnButton9;
lv_obj_t *uic_deviceInfoLabel;
lv_obj_t *uic_ContainerA5;
lv_obj_t *uic_serial_number;
lv_obj_t *uic_customerID;
lv_obj_t *uic_activationDate;
lv_obj_t *uic_serviceInfoButton;
lv_obj_t *uic_serviceInfoPanel;
lv_obj_t *uic_returnButton10;
lv_obj_t *uic_serviceInfoLabel;
lv_obj_t *uic_ContainerA6;
lv_obj_t *uic_servicesintervals;

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t *ui_imgset_882430644[1] = {&ui_img_640283455};
const lv_img_dsc_t *ui_imgset_return_[1] = {&ui_img_return_66_png};
const lv_img_dsc_t *ui_imgset_wifi_[1] = {&ui_img_wifi_4_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_mainScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      mainScreen( e );
}
}

void ui_event_returnButton13( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_controlSettingScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_controlSettingScreen_screen_init);
      _ui_screen_delete( &ui_mainScreen);
}
}

void ui_event_controlSettingScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      settingScreen( e );
}
}

void ui_event_returnButton4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_mainScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_mainScreen_screen_init);
      _ui_screen_delete( &ui_controlSettingScreen);
}
}

void ui_event_SettingCTRL( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_processSettingScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_processSettingScreen_screen_init);
      _ui_screen_delete( &ui_controlSettingScreen);
}
}

void ui_event_Advanced_Setting_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_addvansedSettingScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_addvansedSettingScreen_screen_init);
      _ui_screen_delete( &ui_controlSettingScreen);
}
}

void ui_event_TurnOffCTRL( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      turnOffCtrl_Checked( e );
      _ui_flag_modify( ui_COOLER_IS__OFF, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_COOLER_IS__ON, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      turnOffCtrl_Unchecked( e );
      _ui_flag_modify( ui_COOLER_IS__OFF, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_COOLER_IS__ON, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_Status_info_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_statusScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_statusScreen_screen_init);
      _ui_screen_delete( &ui_controlSettingScreen);
}
}

void ui_event_processSettingScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      processSettingScreen( e );
}
}

void ui_event_returnButton5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_controlSettingScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_controlSettingScreen_screen_init);
      _ui_screen_delete( &ui_processSettingScreen);
}
}

void ui_event_Setting_Save_btn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      submit_process_setting( e );
}
}

void ui_event_Compressor_Range_Plus_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_spinbox_step( ui_Compressor_Range_Spinbox, 1);
}
}

void ui_event_Compressor_Range_Minus_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_spinbox_step( ui_Compressor_Range_Spinbox, -1);
}
}

void ui_event_Compressor_Offset_Plus_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_spinbox_step( ui_Compressor_Offste_Spinbox, 1);
}
}

void ui_event_Compressor_Offset_Minus_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_spinbox_step( ui_Compressor_Offste_Spinbox, -1);
}
}

void ui_event_High_Temp_Alarm_Plus_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_spinbox_step( ui_High_Temp_Alarm_Spinbox, 1);
}
}

void ui_event_High_Temp_Alarm_Minus_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_spinbox_step( ui_High_Temp_Alarm_Spinbox, -1);
}
}

void ui_event_PressureAlarmSwitch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_PressureAlarmSwitch_ONlabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_PressureAlarmSwitch_OFFlabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_PressureAlarmSwitch_OFFlabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_PressureAlarmSwitch_ONlabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_TempAlarmSwitch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_TempAlarmSwitch_ONlabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_TempAlarmSwitch_OFFlabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_state_modify( ui_High_Temp_Alarm_Plus_Button, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_High_Temp_Alarm_Minus_Button, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_High_Temp_Alarm_Spinbox, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_TempAlarmSwitch_OFFlabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_TempAlarmSwitch_ONlabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_state_modify( ui_High_Temp_Alarm_Spinbox, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_High_Temp_Alarm_Plus_Button, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_High_Temp_Alarm_Minus_Button, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
}
}

void ui_event_addvansedSettingScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      addvancedSettingScreen( e );
}
}

void ui_event_returnButton14( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_controlSettingScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_controlSettingScreen_screen_init);
      _ui_screen_delete( &ui_addvansedSettingScreen);
}
}

void ui_event_Setting_Save_btn_in_advanced_Screen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      submit_advance_setting( e );
}
}

void ui_event_AntiFreeze_Temp_Range_Plus_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_spinbox_step( ui_AntiFreeze_Temp_Range_Spinbox, 1);
}
}

void ui_event_AntiFreeze_Temp_Range_Minus_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_spinbox_step( ui_AntiFreeze_Temp_Range_Spinbox, -1);
}
}

void ui_event_AntiFreeze_Temp_Offset_Plus_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_spinbox_step( ui_AntiFreeze_Temp_Offset_Spinbox, 1);
}
}

void ui_event_AntiFreeze_Temp_Offset_Minus_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_spinbox_step( ui_AntiFreeze_Temp_Offset_Spinbox, -1);
}
}

void ui_event_Compressor_Rest_Time_Plus_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_spinbox_step( ui_Compressor_Rest_Time_Spinbox, 1);
}
}

void ui_event_Compressor_Rest_Time_Minus_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_spinbox_step( ui_Compressor_Rest_Time_Spinbox, -1);
}
}

void ui_event_Filter_Alarm_Plus_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_spinbox_step( ui_Filter_Alarm_Spinbox, 1);
}
}

void ui_event_Filter_Alarm_Minus_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_spinbox_step( ui_Filter_Alarm_Spinbox, -1);
}
}

void ui_event_fan_2_range_Plus_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_spinbox_step( ui_fan_2_range_Spinbox, 1);
}
}

void ui_event_fan_2_range_Minus_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_spinbox_step( ui_fan_2_range_Spinbox, -1);
}
}

void ui_event_fan_2_Switch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_disable_fan_2_Label, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_enable_fan_2_Label, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_state_modify( ui_fan_2_range_Minus_Button, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_fan_2_range_Plus_Button, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_fan_2_range_Spinbox, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_fan_2_range_Plus_Button, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_fan_2_range_Spinbox, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_fan_2_range_Minus_Button, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_flag_modify( ui_disable_fan_2_Label, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_enable_fan_2_Label, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_door_alarm_status_Switch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_disable_door_alarm_status_Label, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_enable_door_alarm_status_Label, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_enable_door_alarm_status_Label, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_disable_door_alarm_status_Label, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_filter_alarm_status_Switch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_disable_filter_alarm_status_Label, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_enable_filter_alarm_status_Label, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_enable_filter_alarm_status_Label, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_disable_filter_alarm_status_Label, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_Sensor_Setup_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_sensors_setup_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_open_factory_reset_panel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_factory_reset_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_close_sensor_setup_container_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_sensors_setup_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_state_modify( ui_inlet_Checkbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_outlet_Checkbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_antifreeze_Checkbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_filter_Checkbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}

void ui_event_search_sensor_setup_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      searchingSensors( e );
}
}

void ui_event_inlet_Checkbox( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_outlet_Checkbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_antifreeze_Checkbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_filter_Checkbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}

void ui_event_outlet_Checkbox( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_filter_Checkbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_antifreeze_Checkbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_inlet_Checkbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}

void ui_event_filter_Checkbox( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_antifreeze_Checkbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_outlet_Checkbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_inlet_Checkbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}

void ui_event_antifreeze_Checkbox( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_filter_Checkbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_outlet_Checkbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_inlet_Checkbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}

void ui_event_close_factory_container( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_factory_reset_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_submit_factory_( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      goToFactoryReseting( e );
}
}

void ui_event_statusScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      satusScreen( e );
}
}

void ui_event_returnButton3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_controlSettingScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_controlSettingScreen_screen_init);
      _ui_screen_delete( &ui_statusScreen);
}
}

void ui_event_tempStatusButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_tempStatusPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_serviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_deviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_networkStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_relayStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_alarmStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_tempStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_returnButton11( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_tempStatusPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_serviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_deviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_networkStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_relayStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_alarmStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_tempStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_alarmStatusButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_alarmStatusPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_serviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_deviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_networkStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_relayStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_alarmStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_tempStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_returnButton2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_alarmStatusPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_serviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_deviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_networkStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_relayStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_alarmStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_tempStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_relayStatusButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_relayStatusPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_serviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_deviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_networkStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_relayStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_alarmStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_tempStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_returnButton7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_serviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_deviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_networkStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_relayStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_alarmStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_tempStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_relayStatusPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_networkStatusButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_networkStatusPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_serviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_deviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_networkStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_relayStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_alarmStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_tempStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      show_QR_code( e );
}
}

void ui_event_returnButton8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_serviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_deviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_networkStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_relayStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_alarmStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_tempStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_networkStatusPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_QRcode_Tab, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_Hide_QR_Code_Button, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_show_QR_Code_Button, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_show_QR_Code_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_QRcode_Tab, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_Hide_QR_Code_Button, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_show_QR_Code_Button, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_Hide_QR_Code_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_QRcode_Tab, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_show_QR_Code_Button, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_Hide_QR_Code_Button, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_deviceInfoButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_deviceInfoPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_serviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_deviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_networkStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_relayStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_alarmStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_tempStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_returnButton9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_serviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_deviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_networkStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_relayStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_alarmStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_tempStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_deviceInfoPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_serviceInfoButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_serviceInfoPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_serviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_deviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_networkStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_relayStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_alarmStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_tempStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_returnButton10( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_serviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_deviceInfoButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_networkStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_relayStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_alarmStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_tempStatusButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_serviceInfoPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_mainScreen_screen_init();
ui_controlSettingScreen_screen_init();
ui_processSettingScreen_screen_init();
ui_addvansedSettingScreen_screen_init();
ui_statusScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_mainScreen);
}
