import os
import re

# Directory containing the project
directory = "/Users/mra1380mohammadrezagmail.com/2- Dev/3- Project/IOT Project/Arduino/iot-ctrl-unit/Program"  # 🔹 Change this path

# Exact regex pattern to match and remove the specific comments
comment_pattern = re.compile(r"// This file was generated by SquareLine Studio\n// SquareLine Studio version: SquareLine Studio 1.5.0\n// LVGL version: 8.3.11\n// Project name: SquareLine_Project", re.DOTALL)

# Iterate over all C and C++ files
for root, _, files in os.walk(directory):
    for file in files:
        if file.endswith((".c", ".cpp", ".h", ".hpp")):  # 🔹 Targeted file extensions
            file_path = os.path.join(root, file)

            # Read file content
            with open(file_path, "r", encoding="utf-8") as f:
                content = f.read()

            # Remove the specified comments
            new_content = re.sub(comment_pattern, "", content)

            # Check if the file name as a comment (e.g., // ui_eventc.h) exists anywhere in the file
            if f"// {file}" not in new_content:
                # If the file name as a comment is not found, add it to the first line
                new_content = f"// {file}\n" + new_content

            # Write back the modified content
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(new_content)

print("✅ comment-tool.py ...")
# add to precommit hook ...