// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void mainScreen(lv_event_t * e);
void settingScreen(lv_event_t * e);
void turnOffCtrl_Checked(lv_event_t * e);
void turnOffCtrl_Unchecked(lv_event_t * e);
void processSettingScreen(lv_event_t * e);
void submit_process_setting(lv_event_t * e);
void addvancedSettingScreen(lv_event_t * e);
void submit_advance_setting(lv_event_t * e);
void searchingSensors(lv_event_t * e);
void goToFactoryReseting(lv_event_t * e);
void satusScreen(lv_event_t * e);
void show_QR_code(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
