// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "setting.h"
#include <Arduino.h>

void mainScreen(lv_event_t *e)
{
	// Your code here
}

void settingScreen(lv_event_t *e)
{
	// turnOffCtrl btn
	bool deviceOnStateForBtn;
	deviceOnStateForBtn = getBooleanSetting(DEVICE_ON);

	if (deviceOnStateForBtn)
	{
		lv_obj_add_state(ui_TurnOffCTRL, LV_STATE_CHECKED); // btn checked

		lv_obj_clear_flag(ui_COOLER_IS__ON, LV_OBJ_FLAG_HIDDEN); // unhide COOLER_IS__ON
		lv_obj_add_flag(ui_COOLER_IS__OFF, LV_OBJ_FLAG_HIDDEN);	 // hide COOLER_IS__OFF
	}
	else
	{
		lv_obj_clear_state(ui_TurnOffCTRL, LV_STATE_CHECKED); // btn unchecked

		lv_obj_clear_flag(ui_COOLER_IS__OFF, LV_OBJ_FLAG_HIDDEN); // unhide COOLER_IS__OFF
	}
}

lv_timer_t *coolerStatusTimer = NULL; // store the timer

void showCoolerStatusOn(lv_timer_t *timer)
{
	// Hide the "COOLER IS : OFF" label
	lv_obj_add_flag(ui_COOLER_IS__OFF, LV_OBJ_FLAG_HIDDEN);

	// Update text and show the "COOLER IS : ON" label
	lv_label_set_text(ui_COOLER_IS__ON, "COOLER IS : ON");
	lv_obj_clear_flag(ui_COOLER_IS__ON, LV_OBJ_FLAG_HIDDEN);

	// Delete the timer
	lv_timer_del(timer);
	coolerStatusTimer = NULL;
}

void showCoolerStatusOff(lv_timer_t *timer)
{
	// Hide the "COOLER IS : ON" label
	lv_obj_add_flag(ui_COOLER_IS__ON, LV_OBJ_FLAG_HIDDEN);

	// Update text and show the "COOLER IS : OFF" label
	lv_label_set_text(ui_COOLER_IS__OFF, "COOLER IS : OFF");
	lv_obj_clear_flag(ui_COOLER_IS__OFF, LV_OBJ_FLAG_HIDDEN);

	// Delete the timer
	lv_timer_del(timer);
	coolerStatusTimer = NULL;
}

void turnOffCtrl_Checked(lv_event_t *e)
{
	// Store device state as ON
	setBooleanSetting(DEVICE_ON, true);

	// Hide the "COOLER IS : OFF" label
	lv_obj_add_flag(ui_COOLER_IS__OFF, LV_OBJ_FLAG_HIDDEN);

	// Set New label: "TURNING ON..."
	lv_label_set_text(ui_COOLER_IS__ON, "TURNING ON...");
	lv_obj_clear_flag(ui_COOLER_IS__ON, LV_OBJ_FLAG_HIDDEN);

	// If a previous timer exists, delete it before creating a new one
	if (coolerStatusTimer != NULL)
	{
		lv_timer_del(coolerStatusTimer);
		coolerStatusTimer = NULL;
	}

	// Create a new timer to update the final status after 7 seconds
	coolerStatusTimer = lv_timer_create(showCoolerStatusOn, 5000, NULL);
}

void turnOffCtrl_Unchecked(lv_event_t *e)
{
	// Store device state as OFF
	setBooleanSetting(DEVICE_ON, false);

	// Hide the "COOLER IS : ON" label
	lv_obj_add_flag(ui_COOLER_IS__ON, LV_OBJ_FLAG_HIDDEN);

	// Set new label: "TURNING OFF..." label
	lv_label_set_text(ui_COOLER_IS__OFF, "TURNING OFF...");
	lv_obj_clear_flag(ui_COOLER_IS__OFF, LV_OBJ_FLAG_HIDDEN);

	// If a previous timer exists, delete it before creating a new one
	if (coolerStatusTimer != NULL)
	{
		lv_timer_del(coolerStatusTimer);
		coolerStatusTimer = NULL;
	}

	// Create a new timer to update the final status after 7 seconds
	coolerStatusTimer = lv_timer_create(showCoolerStatusOff, 5000, NULL);
}

void processSettingScreen(lv_event_t *e)
{
	int compressorTempSpinbox;
	compressorTempSpinbox = getNumericSetting(COMPRESSOR_TEMP);
	lv_spinbox_set_value(ui_Compressor_Range_Spinbox, compressorTempSpinbox);

	int compressorOffsetSpinbox;
	compressorOffsetSpinbox = getNumericSetting(COMPRESSOR_RANGE);
	lv_spinbox_set_value(ui_Compressor_Offste_Spinbox, compressorOffsetSpinbox);

	int highTempAlarmSpinbox;
	highTempAlarmSpinbox = getNumericSetting(HIGH_TEMP_WARNING);
	lv_spinbox_set_value(ui_High_Temp_Alarm_Spinbox, highTempAlarmSpinbox);

	bool pressureAlarmSwitch;
	pressureAlarmSwitch = getBooleanSetting(PRESSURE_WARNING_ON);
	if (pressureAlarmSwitch)
	{
		// true - checked
		lv_obj_add_state(ui_PressureAlarmSwitch, LV_STATE_CHECKED);
		lv_obj_clear_flag(ui_PressureAlarmSwitch_ONlabel, LV_OBJ_FLAG_HIDDEN); // "ON" Flag
		lv_obj_add_flag(ui_PressureAlarmSwitch_OFFlabel, LV_OBJ_FLAG_HIDDEN);  // "OFF" Flag
	}
	else
	{
		// false - unchecked
		lv_obj_clear_state(ui_PressureAlarmSwitch, LV_STATE_CHECKED);
		lv_obj_add_flag(ui_PressureAlarmSwitch_ONlabel, LV_OBJ_FLAG_HIDDEN);	// "ON" Flag
		lv_obj_clear_flag(ui_PressureAlarmSwitch_OFFlabel, LV_OBJ_FLAG_HIDDEN); // "OFF" Flag
	}

	bool tempAlarmSwitch;
	tempAlarmSwitch = getBooleanSetting(TEMP_WARNING_ON);
	if (tempAlarmSwitch)
	{
		// true - checked
		lv_obj_add_state(ui_TempAlarmSwitch, LV_STATE_CHECKED);
		lv_obj_clear_flag(ui_TempAlarmSwitch_ONlabel, LV_OBJ_FLAG_HIDDEN); // "ON" Flag
		lv_obj_add_flag(ui_TempAlarmSwitch_OFFlabel, LV_OBJ_FLAG_HIDDEN);  // "OFF" Flag

		_ui_state_modify(ui_High_Temp_Alarm_Plus_Button, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
		_ui_state_modify(ui_High_Temp_Alarm_Minus_Button, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
		_ui_state_modify(ui_High_Temp_Alarm_Spinbox, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
	}
	else
	{
		// false - unchecked
		lv_obj_clear_state(ui_TempAlarmSwitch, LV_STATE_CHECKED);
		lv_obj_add_flag(ui_TempAlarmSwitch_ONlabel, LV_OBJ_FLAG_HIDDEN);	// "ON" Flag
		lv_obj_clear_flag(ui_TempAlarmSwitch_OFFlabel, LV_OBJ_FLAG_HIDDEN); // "OFF" Flag

		_ui_state_modify(ui_High_Temp_Alarm_Spinbox, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
		_ui_state_modify(ui_High_Temp_Alarm_Plus_Button, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
		_ui_state_modify(ui_High_Temp_Alarm_Minus_Button, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
	}
}

static void update_save_label(lv_timer_t *timer)
{
	static int step = 0;
	const char *texts[] = {"Saving", "Saved", "Save"};

	lv_label_set_text(ui_Setting_Save_btn_label, texts[step]);

	step++;
	if (step >= 3)
	{
		step = 0;
		lv_timer_del(timer); // delete timer
	}
}

void animate_save_label()
{
	lv_label_set_text(ui_Setting_Save_btn_label, "Save");
	lv_timer_create(update_save_label, 1000, NULL); // 1000ms
}

void submit_process_setting(lv_event_t *e)
{
	animate_save_label();

	int compressorTempValue = lv_spinbox_get_value(ui_Compressor_Range_Spinbox);
	int compressorOffsetValue = lv_spinbox_get_value(ui_Compressor_Offste_Spinbox);
	int highTempAlarmValue = lv_spinbox_get_value(ui_High_Temp_Alarm_Spinbox);

	bool pressureAlarmState = lv_obj_has_state(ui_PressureAlarmSwitch, LV_STATE_CHECKED);
	bool tempAlarmState = lv_obj_has_state(ui_TempAlarmSwitch, LV_STATE_CHECKED);

	setNumericSetting(COMPRESSOR_TEMP, compressorTempValue);
	setNumericSetting(COMPRESSOR_RANGE, compressorOffsetValue);
	setNumericSetting(HIGH_TEMP_WARNING, highTempAlarmValue);

	setBooleanSetting(PRESSURE_WARNING_ON, pressureAlarmState);
	setBooleanSetting(TEMP_WARNING_ON, tempAlarmState);
}

void addvancedSettingScreen(lv_event_t *e)
{
	// Your code here
}

void submit_advance_setting(lv_event_t *e)
{
	// Your code here
}

void searchingSensors(lv_event_t *e)
{
	// Your code here
}

void goToFactoryReseting(lv_event_t *e)
{
	// Your code here
}

void satusScreen(lv_event_t *e)
{
	// Your code here
}

void show_QR_code(lv_event_t *e)
{
	// Your code here
}
