// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_wifiScreen_screen_init(void)
{
ui_wifiScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_wifiScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_wifiScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wifiScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifisettingscreenlabel = lv_label_create(ui_wifiScreen);
lv_obj_set_width( ui_wifisettingscreenlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifisettingscreenlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifisettingscreenlabel, 0 );
lv_obj_set_y( ui_wifisettingscreenlabel, -100 );
lv_obj_set_align( ui_wifisettingscreenlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wifisettingscreenlabel,"WI-FI SETTING");
lv_obj_set_style_text_color(ui_wifisettingscreenlabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wifisettingscreenlabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wifisettingscreenlabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Time_Status_screen_1 = lv_label_create(ui_wifiScreen);
lv_obj_set_width( ui_Time_Status_screen_1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Time_Status_screen_1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Time_Status_screen_1, 120 );
lv_obj_set_y( ui_Time_Status_screen_1, -100 );
lv_obj_set_align( ui_Time_Status_screen_1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Time_Status_screen_1,"T: ");
lv_obj_set_style_text_color(ui_Time_Status_screen_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Time_Status_screen_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Time_Status_screen_1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_returnButton1 = lv_btn_create(ui_wifiScreen);
lv_obj_set_width( ui_returnButton1, 60);
lv_obj_set_height( ui_returnButton1, 30);
lv_obj_set_x( ui_returnButton1, -125 );
lv_obj_set_y( ui_returnButton1, -100 );
lv_obj_set_align( ui_returnButton1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_returnButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_returnButton1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_returnButton1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_returnButton1, lv_color_hex(0x0D0246), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_returnButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_returnButton1, &ui_img_return_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_width(ui_returnButton1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_returnButton1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_returnButton1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_returnButton1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_networksearch = lv_dropdown_create(ui_wifiScreen);
lv_dropdown_set_options( ui_networksearch, "" );
lv_dropdown_set_text( ui_networksearch, "Select Ntwork");
lv_obj_set_width( ui_networksearch, 190);
lv_obj_set_height( ui_networksearch, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_networksearch, -26 );
lv_obj_set_y( ui_networksearch, -60 );
lv_obj_set_align( ui_networksearch, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_networksearch, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_networksearch, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_text_font(ui_networksearch, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_networksearch, lv_color_hex(0x080041), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_networksearch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_networksearch, 1, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_ssidInputLabel = lv_label_create(ui_wifiScreen);
lv_obj_set_width( ui_ssidInputLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ssidInputLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ssidInputLabel, -140 );
lv_obj_set_y( ui_ssidInputLabel, -60 );
lv_obj_set_align( ui_ssidInputLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ssidInputLabel,"SSID:");
lv_obj_set_style_text_font(ui_ssidInputLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiDisconnectBtn = lv_btn_create(ui_wifiScreen);
lv_obj_set_width( ui_WifiDisconnectBtn, 85);
lv_obj_set_height( ui_WifiDisconnectBtn, 33);
lv_obj_set_x( ui_WifiDisconnectBtn, 115 );
lv_obj_set_y( ui_WifiDisconnectBtn, -60 );
lv_obj_set_align( ui_WifiDisconnectBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WifiDisconnectBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_WifiDisconnectBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_WifiDisconnectBtn, lv_color_hex(0xFF0400), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WifiDisconnectBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_WifiDisconnectBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_WifiDisconnectBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_WifiDisconnectBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_WifiDisconnectBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiDisconnectText = lv_label_create(ui_wifiScreen);
lv_obj_set_width( ui_WifiDisconnectText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WifiDisconnectText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WifiDisconnectText, 115 );
lv_obj_set_y( ui_WifiDisconnectText, -60 );
lv_obj_set_align( ui_WifiDisconnectText, LV_ALIGN_CENTER );
lv_label_set_text(ui_WifiDisconnectText,"Disconnect");
lv_obj_clear_flag( ui_WifiDisconnectText, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_text_color(ui_WifiDisconnectText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_WifiDisconnectText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_WifiDisconnectText, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Status_Container = lv_obj_create(ui_wifiScreen);
lv_obj_remove_style_all(ui_Status_Container);
lv_obj_set_width( ui_Status_Container, 210);
lv_obj_set_height( ui_Status_Container, 100);
lv_obj_set_x( ui_Status_Container, -45 );
lv_obj_set_y( ui_Status_Container, 15 );
lv_obj_set_align( ui_Status_Container, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Status_Container,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_Status_Container, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Status_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WIFI_Status_WifiScreen = lv_label_create(ui_Status_Container);
lv_obj_set_width( ui_WIFI_Status_WifiScreen, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WIFI_Status_WifiScreen, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WIFI_Status_WifiScreen, -130 );
lv_obj_set_y( ui_WIFI_Status_WifiScreen, 20 );
lv_obj_set_align( ui_WIFI_Status_WifiScreen, LV_ALIGN_CENTER );
lv_label_set_text(ui_WIFI_Status_WifiScreen,"WI-FI :");
lv_obj_set_style_text_font(ui_WIFI_Status_WifiScreen, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Cloud_Connection_Status = lv_label_create(ui_Status_Container);
lv_obj_set_width( ui_Cloud_Connection_Status, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Cloud_Connection_Status, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Cloud_Connection_Status, -120 );
lv_obj_set_y( ui_Cloud_Connection_Status, 55 );
lv_obj_set_align( ui_Cloud_Connection_Status, LV_ALIGN_CENTER );
lv_label_set_text(ui_Cloud_Connection_Status,"CLOUD :");
lv_obj_set_style_text_font(ui_Cloud_Connection_Status, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_server_handshake_btn = lv_btn_create(ui_wifiScreen);
lv_obj_set_width( ui_server_handshake_btn, 85);
lv_obj_set_height( ui_server_handshake_btn, 33);
lv_obj_set_x( ui_server_handshake_btn, 115 );
lv_obj_set_y( ui_server_handshake_btn, 20 );
lv_obj_set_align( ui_server_handshake_btn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_server_handshake_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_server_handshake_btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_server_handshake_btn, lv_color_hex(0xD7D7D7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_server_handshake_btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_server_handshake_btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_server_handshake_btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_server_handshake_btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_server_handshake_btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_server_handshake_btn_text = lv_label_create(ui_wifiScreen);
lv_obj_set_width( ui_server_handshake_btn_text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_server_handshake_btn_text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_server_handshake_btn_text, 115 );
lv_obj_set_y( ui_server_handshake_btn_text, 19 );
lv_obj_set_align( ui_server_handshake_btn_text, LV_ALIGN_CENTER );
lv_label_set_text(ui_server_handshake_btn_text,"Check");
lv_obj_clear_flag( ui_server_handshake_btn_text, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_text_color(ui_server_handshake_btn_text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_server_handshake_btn_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_server_handshake_btn_text, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_passScreenPopup = lv_btn_create(ui_wifiScreen);
lv_obj_set_width( ui_passScreenPopup, 85);
lv_obj_set_height( ui_passScreenPopup, 33);
lv_obj_set_x( ui_passScreenPopup, 115 );
lv_obj_set_y( ui_passScreenPopup, -20 );
lv_obj_set_align( ui_passScreenPopup, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_passScreenPopup, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_passScreenPopup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_passScreenPopup, lv_color_hex(0x00BE10), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_passScreenPopup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_passScreenPopup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_passScreenPopup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_passScreenPopup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_passScreenPopup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_passScreenPopuplabel = lv_label_create(ui_wifiScreen);
lv_obj_set_width( ui_passScreenPopuplabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_passScreenPopuplabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_passScreenPopuplabel, 115 );
lv_obj_set_y( ui_passScreenPopuplabel, -21 );
lv_obj_set_align( ui_passScreenPopuplabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_passScreenPopuplabel,"Connect");
lv_obj_set_style_text_color(ui_passScreenPopuplabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_passScreenPopuplabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_passScreenPopuplabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi_connected_Status_image = lv_img_create(ui_wifiScreen);
lv_img_set_src(ui_wifi_connected_Status_image, &ui_img_wifi_4_png);
lv_obj_set_width( ui_wifi_connected_Status_image, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_wifi_connected_Status_image, LV_SIZE_CONTENT);   /// 30
lv_obj_set_x( ui_wifi_connected_Status_image, -125 );
lv_obj_set_y( ui_wifi_connected_Status_image, 90 );
lv_obj_set_align( ui_wifi_connected_Status_image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_connected_Status_image, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifi_connected_Status_image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wifi_not_connected_Status_image = lv_img_create(ui_wifiScreen);
lv_img_set_src(ui_wifi_not_connected_Status_image, &ui_img_534919753);
lv_obj_set_width( ui_wifi_not_connected_Status_image, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_wifi_not_connected_Status_image, LV_SIZE_CONTENT);   /// 30
lv_obj_set_x( ui_wifi_not_connected_Status_image, -125 );
lv_obj_set_y( ui_wifi_not_connected_Status_image, 90 );
lv_obj_set_align( ui_wifi_not_connected_Status_image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_not_connected_Status_image, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifi_not_connected_Status_image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_cloud_connected_Status_image = lv_img_create(ui_wifiScreen);
lv_img_set_src(ui_cloud_connected_Status_image, &ui_img_cloud_png);
lv_obj_set_width( ui_cloud_connected_Status_image, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_cloud_connected_Status_image, LV_SIZE_CONTENT);   /// 30
lv_obj_set_x( ui_cloud_connected_Status_image, -75 );
lv_obj_set_y( ui_cloud_connected_Status_image, 90 );
lv_obj_set_align( ui_cloud_connected_Status_image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_cloud_connected_Status_image, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_cloud_connected_Status_image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_cloud_not_connected_Status_image = lv_img_create(ui_wifiScreen);
lv_img_set_src(ui_cloud_not_connected_Status_image, &ui_img_1740866726);
lv_obj_set_width( ui_cloud_not_connected_Status_image, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_cloud_not_connected_Status_image, LV_SIZE_CONTENT);   /// 30
lv_obj_set_x( ui_cloud_not_connected_Status_image, -75 );
lv_obj_set_y( ui_cloud_not_connected_Status_image, 90 );
lv_obj_set_align( ui_cloud_not_connected_Status_image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_cloud_not_connected_Status_image, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_cloud_not_connected_Status_image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Keyboard_Panel = lv_obj_create(ui_wifiScreen);
lv_obj_set_width( ui_Keyboard_Panel, 324);
lv_obj_set_height( ui_Keyboard_Panel, 244);
lv_obj_set_align( ui_Keyboard_Panel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Keyboard_Panel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Keyboard_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Keyboard_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Keyboard_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Keyboard_Panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi_Setting_Submit_btn = lv_btn_create(ui_Keyboard_Panel);
lv_obj_set_width( ui_wifi_Setting_Submit_btn, 60);
lv_obj_set_height( ui_wifi_Setting_Submit_btn, 30);
lv_obj_set_x( ui_wifi_Setting_Submit_btn, 125 );
lv_obj_set_y( ui_wifi_Setting_Submit_btn, -100 );
lv_obj_set_align( ui_wifi_Setting_Submit_btn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_Setting_Submit_btn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_wifi_Setting_Submit_btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_wifi_Setting_Submit_btn, lv_color_hex(0x00BE10), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wifi_Setting_Submit_btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_wifi_Setting_Submit_btn, lv_color_hex(0x080041), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_wifi_Setting_Submit_btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_wifi_Setting_Submit_btn, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_wifi_Setting_Submit_btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_wifi_Setting_Submit_btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_wifi_Setting_Submit_btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_wifi_Setting_Submit_btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi_Setting_Submit_btn_label = lv_label_create(ui_Keyboard_Panel);
lv_obj_set_width( ui_wifi_Setting_Submit_btn_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_Setting_Submit_btn_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_Setting_Submit_btn_label, 125 );
lv_obj_set_y( ui_wifi_Setting_Submit_btn_label, -101 );
lv_obj_set_align( ui_wifi_Setting_Submit_btn_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_wifi_Setting_Submit_btn_label,"Connect");
lv_obj_add_flag( ui_wifi_Setting_Submit_btn_label, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_wifi_Setting_Submit_btn_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wifi_Setting_Submit_btn_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wifi_Setting_Submit_btn_label, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiPasswordTareaBase = lv_textarea_create(ui_Keyboard_Panel);
lv_obj_set_width( ui_wifiPasswordTareaBase, 180);
lv_obj_set_height( ui_wifiPasswordTareaBase, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_wifiPasswordTareaBase, 0 );
lv_obj_set_y( ui_wifiPasswordTareaBase, -100 );
lv_obj_set_align( ui_wifiPasswordTareaBase, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_wifiPasswordTareaBase,512);
lv_textarea_set_placeholder_text(ui_wifiPasswordTareaBase,"Password...");
lv_textarea_set_one_line(ui_wifiPasswordTareaBase,true);
lv_obj_add_state( ui_wifiPasswordTareaBase, LV_STATE_FOCUSED );     /// States
lv_obj_add_flag( ui_wifiPasswordTareaBase, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_wifiPasswordTareaBase, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_text_font(ui_wifiPasswordTareaBase, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_wifiPasswordTareaBase, lv_color_hex(0xB6B4FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_wifiPasswordTareaBase, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_wifiPasswordTareaBase, 1, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_keyboardWifiScreen = lv_keyboard_create(ui_Keyboard_Panel);
lv_obj_set_width( ui_keyboardWifiScreen, 320);
lv_obj_set_height( ui_keyboardWifiScreen, 200);
lv_obj_set_x( ui_keyboardWifiScreen, 0 );
lv_obj_set_y( ui_keyboardWifiScreen, 20 );
lv_obj_set_align( ui_keyboardWifiScreen, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_keyboardWifiScreen, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_bg_color(ui_keyboardWifiScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_keyboardWifiScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_keyboardWifiScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_keyboardWifiScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_keyboardWifiScreen, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_keyboardWifiScreen, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_keyboardWifiScreen, lv_color_hex(0x0E0055), LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_keyboardWifiScreen, 255, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_keyboardWifiScreen, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_keyboardWifiScreen, 255, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_keyboardWifiScreen, &lv_font_montserrat_14, LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_backButton = lv_btn_create(ui_Keyboard_Panel);
lv_obj_set_width( ui_backButton, 60);
lv_obj_set_height( ui_backButton, 30);
lv_obj_set_x( ui_backButton, -125 );
lv_obj_set_y( ui_backButton, -100 );
lv_obj_set_align( ui_backButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_backButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_backButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_backButton, lv_color_hex(0x080041), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_backButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_backButton, &ui_img_return_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_width(ui_backButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_backButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_backButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_backButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_returnButton1, ui_event_returnButton1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_networksearch, ui_event_networksearch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WifiDisconnectBtn, ui_event_WifiDisconnectBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WIFI_Status_WifiScreen, ui_event_WIFI_Status_WifiScreen, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Cloud_Connection_Status, ui_event_Cloud_Connection_Status, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_server_handshake_btn, ui_event_server_handshake_btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_passScreenPopup, ui_event_passScreenPopup, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifi_Setting_Submit_btn, ui_event_wifi_Setting_Submit_btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifiPasswordTareaBase, ui_event_wifiPasswordTareaBase, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_keyboardWifiScreen,ui_wifiPasswordTareaBase);
lv_obj_add_event_cb(ui_backButton, ui_event_backButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifiScreen, ui_event_wifiScreen, LV_EVENT_ALL, NULL);
uic_wifiScreen = ui_wifiScreen;
uic_wifisettingscreenlabel = ui_wifisettingscreenlabel;
uic_Time_Status_screen_1 = ui_Time_Status_screen_1;
uic_returnButton1 = ui_returnButton1;
uic_networksearch = ui_networksearch;
uic_ssidInputLabel = ui_ssidInputLabel;
uic_WifiDisconnectBtn = ui_WifiDisconnectBtn;
uic_WifiDisconnectText = ui_WifiDisconnectText;
uic_Status_Container = ui_Status_Container;
uic_WIFI_Status_WifiScreen = ui_WIFI_Status_WifiScreen;
uic_Cloud_Connection_Status = ui_Cloud_Connection_Status;
uic_server_handshake_btn = ui_server_handshake_btn;
uic_server_handshake_btn_text = ui_server_handshake_btn_text;
uic_passScreenPopup = ui_passScreenPopup;
uic_passScreenPopuplabel = ui_passScreenPopuplabel;
uic_wifi_connected_Status_image = ui_wifi_connected_Status_image;
uic_wifi_not_connected_Status_image = ui_wifi_not_connected_Status_image;
uic_cloud_connected_Status_image = ui_cloud_connected_Status_image;
uic_cloud_not_connected_Status_image = ui_cloud_not_connected_Status_image;
uic_Keyboard_Panel = ui_Keyboard_Panel;
uic_wifi_Setting_Submit_btn = ui_wifi_Setting_Submit_btn;
uic_wifi_Setting_Submit_btn_label = ui_wifi_Setting_Submit_btn_label;
uic_wifiPasswordTareaBase = ui_wifiPasswordTareaBase;
uic_keyboardWifiScreen = ui_keyboardWifiScreen;
uic_backButton = ui_backButton;

}
