// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////
#include "ui_Boot_Screen.h"
#include "ui_controlSettingScreen.h"
#include "ui_processSettingScreen.h"
#include "ui_addvansedSettingScreen.h"
#include "ui_statusScreen.h"
#include "ui_mainScreen.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * loadingIMG_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1274595566);   // assets/wallpapersden.com_77016-5120x3415.png
LV_IMG_DECLARE( ui_img_1575678365);   // assets/logo-min.png
LV_IMG_DECLARE( ui_img_loading_png);   // assets/loading.png
LV_IMG_DECLARE( ui_img_4413586_480x480_png);   // assets/4413586_480x480.png
LV_IMG_DECLARE( ui_img_return_png);   // assets/return.png
LV_IMG_DECLARE( ui_img_278418788);   // assets/setting (2).png
LV_IMG_DECLARE( ui_img_worker_png);   // assets/worker.png
LV_IMG_DECLARE( ui_img_68039786);   // assets/off (1).png
LV_IMG_DECLARE( ui_img_info_png);   // assets/info.png
LV_IMG_DECLARE( ui_img_plus_png);   // assets/plus.png
LV_IMG_DECLARE( ui_img_1731839073);   // assets/minus (1).png
LV_IMG_DECLARE( ui_img_1019942150);   // assets/danger (3).png
LV_IMG_DECLARE( ui_img_return_66_png);   // assets/return 66.png
LV_IMG_DECLARE( ui_img_unread_png);   // assets/unread.png
LV_IMG_DECLARE( ui_img_temperature_png);   // assets/temperature.png
LV_IMG_DECLARE( ui_img_1101012385);   // assets/danger (2).png
LV_IMG_DECLARE( ui_img_sensor_png);   // assets/sensor.png
LV_IMG_DECLARE( ui_img_120570296);   // assets/sync-problem.png
LV_IMG_DECLARE( ui_img_wifi_png);   // assets/wifi.png
LV_IMG_DECLARE( ui_img_983251955);   // assets/qr-code (4).png
LV_IMG_DECLARE( ui_img_close_png);   // assets/close.png
LV_IMG_DECLARE( ui_img_1437619218);   // assets/info (17).png
LV_IMG_DECLARE( ui_img_18821776);   // assets/technical-support.png
LV_IMG_DECLARE( ui_img_menu43_png);   // assets/menu43.png
LV_IMG_DECLARE( ui_img_165651551);   // assets/power (4).png
LV_IMG_DECLARE( ui_img_165652574);   // assets/power (5).png
LV_IMG_DECLARE( ui_img_300499993);   // assets/cooling-fan (6).png
LV_IMG_DECLARE( ui_img_300505244);   // assets/cooling-fan (5).png
LV_IMG_DECLARE( ui_img_835894428);   // assets/high-temprature (4).png
LV_IMG_DECLARE( ui_img_1488402037);   // assets/low-temprature.png
LV_IMG_DECLARE( ui_img_pressure_png);   // assets/pressure.png
LV_IMG_DECLARE( ui_img_31615732);   // assets/dashboard (6).png
LV_IMG_DECLARE( ui_img_2101917800);   // assets/door (6).png
LV_IMG_DECLARE( ui_img_778269571);   // assets/door (5).png
LV_IMG_DECLARE( ui_img_4413586_92912_png);   // assets/4413586_92912.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
