// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Boot_Screen_screen_init(void)
{
ui_Boot_Screen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Boot_Screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Boot_Screen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Boot_Screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Boot_Screen, &ui_img_1234_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_boot_Image = lv_img_create(ui_Boot_Screen);
lv_img_set_src(ui_boot_Image, &ui_img_884211525);
lv_obj_set_width( ui_boot_Image, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_boot_Image, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_boot_Image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_boot_Image, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_boot_Image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_loading_img = lv_img_create(ui_Boot_Screen);
lv_img_set_src(ui_loading_img, &ui_img_loading_png);
lv_obj_set_width( ui_loading_img, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_loading_img, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_loading_img, 0 );
lv_obj_set_y( ui_loading_img, 100 );
lv_obj_set_align( ui_loading_img, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_loading_img, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_loading_img, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Boot_Screen, ui_event_Boot_Screen, LV_EVENT_ALL, NULL);
uic_Boot_Screen = ui_Boot_Screen;
uic_boot_Image = ui_boot_Image;
uic_loading_img = ui_loading_img;

}
