// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_BOOT_SCREEN_H
#define UI_BOOT_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Boot_Screen
extern void ui_Boot_Screen_screen_init(void);
extern void ui_Boot_Screen_screen_destroy(void);
extern void ui_event_Boot_Screen( lv_event_t * e);
extern lv_obj_t *ui_Boot_Screen;
extern lv_obj_t *ui_boot_Image;
extern lv_obj_t *ui_loading_img;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Boot_Screen;
extern lv_obj_t *uic_boot_Image;
extern lv_obj_t *uic_loading_img;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

