// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_controlSettingScreen_screen_init(void)
{
ui_controlSettingScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_controlSettingScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_controlSettingScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_controlSettingScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_controlSettingScreen, &ui_img_1234_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_opa(ui_controlSettingScreen, 128, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_returnButton4 = lv_btn_create(ui_controlSettingScreen);
lv_obj_set_width( ui_returnButton4, 60);
lv_obj_set_height( ui_returnButton4, 30);
lv_obj_set_x( ui_returnButton4, -125 );
lv_obj_set_y( ui_returnButton4, -100 );
lv_obj_set_align( ui_returnButton4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_returnButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_returnButton4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_returnButton4, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_returnButton4, lv_color_hex(0x0D0246), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_returnButton4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_returnButton4, &ui_img_return_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_width(ui_returnButton4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_returnButton4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_returnButton4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_returnButton4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_settingscreenlabel = lv_label_create(ui_controlSettingScreen);
lv_obj_set_width( ui_settingscreenlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_settingscreenlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_settingscreenlabel, 0 );
lv_obj_set_y( ui_settingscreenlabel, -100 );
lv_obj_set_align( ui_settingscreenlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_settingscreenlabel,"SETTING");
lv_obj_set_style_text_color(ui_settingscreenlabel, lv_color_hex(0x080041), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_settingscreenlabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_settingscreenlabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingCTRL = lv_btn_create(ui_controlSettingScreen);
lv_obj_set_width( ui_SettingCTRL, 70);
lv_obj_set_height( ui_SettingCTRL, 70);
lv_obj_set_x( ui_SettingCTRL, -120 );
lv_obj_set_y( ui_SettingCTRL, 0 );
lv_obj_set_align( ui_SettingCTRL, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SettingCTRL, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_SettingCTRL, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SettingCTRL, lv_color_hex(0x0E0055), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingCTRL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_SettingCTRL, &ui_img_278418788, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_width(ui_SettingCTRL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_SettingCTRL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_SettingCTRL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_SettingCTRL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_SettingCTRL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SettingCTRL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SettingCTRL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Advanced_Setting_Button = lv_btn_create(ui_controlSettingScreen);
lv_obj_set_width( ui_Advanced_Setting_Button, 70);
lv_obj_set_height( ui_Advanced_Setting_Button, 70);
lv_obj_set_x( ui_Advanced_Setting_Button, 120 );
lv_obj_set_y( ui_Advanced_Setting_Button, 0 );
lv_obj_set_align( ui_Advanced_Setting_Button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Advanced_Setting_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Advanced_Setting_Button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Advanced_Setting_Button, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Advanced_Setting_Button, lv_color_hex(0x080052), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Advanced_Setting_Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Advanced_Setting_Button, &ui_img_worker_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_width(ui_Advanced_Setting_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Advanced_Setting_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_Advanced_Setting_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_Advanced_Setting_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TurnOffCTRL = lv_btn_create(ui_controlSettingScreen);
lv_obj_set_width( ui_TurnOffCTRL, 70);
lv_obj_set_height( ui_TurnOffCTRL, 70);
lv_obj_set_x( ui_TurnOffCTRL, 40 );
lv_obj_set_y( ui_TurnOffCTRL, 0 );
lv_obj_set_align( ui_TurnOffCTRL, LV_ALIGN_CENTER );
lv_obj_add_state( ui_TurnOffCTRL, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_TurnOffCTRL, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_TurnOffCTRL, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_TurnOffCTRL, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TurnOffCTRL, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TurnOffCTRL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_TurnOffCTRL, &ui_img_68039786, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_width(ui_TurnOffCTRL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_TurnOffCTRL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_TurnOffCTRL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_TurnOffCTRL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_TurnOffCTRL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TurnOffCTRL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TurnOffCTRL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TurnOffCTRL, lv_color_hex(0x00BE10), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_TurnOffCTRL, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Status_info_Button = lv_btn_create(ui_controlSettingScreen);
lv_obj_set_width( ui_Status_info_Button, 70);
lv_obj_set_height( ui_Status_info_Button, 70);
lv_obj_set_x( ui_Status_info_Button, -40 );
lv_obj_set_y( ui_Status_info_Button, 0 );
lv_obj_set_align( ui_Status_info_Button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Status_info_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Status_info_Button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Status_info_Button, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Status_info_Button, lv_color_hex(0x080052), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Status_info_Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Status_info_Button, &ui_img_info_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_width(ui_Status_info_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Status_info_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_Status_info_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_Status_info_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_COOLER_IS__ON = lv_label_create(ui_controlSettingScreen);
lv_obj_set_width( ui_COOLER_IS__ON, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_COOLER_IS__ON, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_COOLER_IS__ON, 0 );
lv_obj_set_y( ui_COOLER_IS__ON, 90 );
lv_obj_set_align( ui_COOLER_IS__ON, LV_ALIGN_CENTER );
lv_label_set_text(ui_COOLER_IS__ON,"COOLER IS : ON");
lv_obj_add_flag( ui_COOLER_IS__ON, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_COOLER_IS__ON, lv_color_hex(0x00BE10), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_COOLER_IS__ON, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_COOLER_IS__ON, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_COOLER_IS__OFF = lv_label_create(ui_controlSettingScreen);
lv_obj_set_width( ui_COOLER_IS__OFF, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_COOLER_IS__OFF, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_COOLER_IS__OFF, 0 );
lv_obj_set_y( ui_COOLER_IS__OFF, 90 );
lv_obj_set_align( ui_COOLER_IS__OFF, LV_ALIGN_CENTER );
lv_label_set_text(ui_COOLER_IS__OFF,"COOLER IS : OFF");
lv_obj_add_flag( ui_COOLER_IS__OFF, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_COOLER_IS__OFF, lv_color_hex(0xFF0400), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_COOLER_IS__OFF, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_COOLER_IS__OFF, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_returnButton4, ui_event_returnButton4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SettingCTRL, ui_event_SettingCTRL, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Advanced_Setting_Button, ui_event_Advanced_Setting_Button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TurnOffCTRL, ui_event_TurnOffCTRL, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Status_info_Button, ui_event_Status_info_Button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_controlSettingScreen, ui_event_controlSettingScreen, LV_EVENT_ALL, NULL);
uic_controlSettingScreen = ui_controlSettingScreen;
uic_returnButton4 = ui_returnButton4;
uic_settingscreenlabel = ui_settingscreenlabel;
uic_SettingCTRL = ui_SettingCTRL;
uic_Advanced_Setting_Button = ui_Advanced_Setting_Button;
uic_TurnOffCTRL = ui_TurnOffCTRL;
uic_Status_info_Button = ui_Status_info_Button;
uic_COOLER_IS__ON = ui_COOLER_IS__ON;
uic_COOLER_IS__OFF = ui_COOLER_IS__OFF;

}
