// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_COOLER_IS__OFF;
lv_obj_t *uic_COOLER_IS__ON;
lv_obj_t *uic_Status_info_Button;
lv_obj_t *uic_TurnOffCTRL;
lv_obj_t *uic_Advanced_Setting_Button;
lv_obj_t *uic_SettingCTRL;
lv_obj_t *uic_settingscreenlabel;
lv_obj_t *uic_returnButton4;
lv_obj_t *uic_controlSettingScreen;
lv_obj_t *ui_controlSettingScreen = NULL;lv_obj_t *ui_returnButton4 = NULL;lv_obj_t *ui_settingscreenlabel = NULL;lv_obj_t *ui_SettingCTRL = NULL;lv_obj_t *ui_Advanced_Setting_Button = NULL;lv_obj_t *ui_TurnOffCTRL = NULL;lv_obj_t *ui_Status_info_Button = NULL;lv_obj_t *ui_COOLER_IS__ON = NULL;lv_obj_t *ui_COOLER_IS__OFF = NULL;
// event funtions
void ui_event_controlSettingScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      settingScreen( e );
}
}

void ui_event_returnButton4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_mainScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_mainScreen_screen_init);
      _ui_screen_delete( &ui_controlSettingScreen);
}
}

void ui_event_SettingCTRL( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_processSettingScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_processSettingScreen_screen_init);
      _ui_screen_delete( &ui_controlSettingScreen);
}
}

void ui_event_Advanced_Setting_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_addvansedSettingScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_addvansedSettingScreen_screen_init);
      _ui_screen_delete( &ui_controlSettingScreen);
}
}

void ui_event_TurnOffCTRL( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      turnOffCtrl_Checked( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      turnOffCtrl_Unchecked( e );
}
}

void ui_event_Status_info_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_statusScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_statusScreen_screen_init);
      _ui_screen_delete( &ui_controlSettingScreen);
}
}

// build funtions

void ui_controlSettingScreen_screen_init(void)
{
ui_controlSettingScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_controlSettingScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_controlSettingScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_controlSettingScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_controlSettingScreen, &ui_img_4413586_480x480_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_returnButton4 = lv_btn_create(ui_controlSettingScreen);
lv_obj_set_width( ui_returnButton4, 80);
lv_obj_set_height( ui_returnButton4, 50);
lv_obj_set_x( ui_returnButton4, -195 );
lv_obj_set_y( ui_returnButton4, -210 );
lv_obj_set_align( ui_returnButton4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_returnButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_returnButton4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_returnButton4, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_returnButton4, lv_color_hex(0x0D0246), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_returnButton4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_returnButton4, &ui_img_return_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_width(ui_returnButton4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_returnButton4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_returnButton4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_returnButton4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_settingscreenlabel = lv_label_create(ui_controlSettingScreen);
lv_obj_set_width( ui_settingscreenlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_settingscreenlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_settingscreenlabel, 0 );
lv_obj_set_y( ui_settingscreenlabel, -210 );
lv_obj_set_align( ui_settingscreenlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_settingscreenlabel,"MENU");
lv_obj_set_style_text_color(ui_settingscreenlabel, lv_color_hex(0x080041), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_settingscreenlabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_settingscreenlabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingCTRL = lv_btn_create(ui_controlSettingScreen);
lv_obj_set_width( ui_SettingCTRL, 105);
lv_obj_set_height( ui_SettingCTRL, 105);
lv_obj_set_x( ui_SettingCTRL, -180 );
lv_obj_set_y( ui_SettingCTRL, 0 );
lv_obj_set_align( ui_SettingCTRL, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SettingCTRL, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_SettingCTRL, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SettingCTRL, lv_color_hex(0x0E0055), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingCTRL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_SettingCTRL, &ui_img_278418788, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_width(ui_SettingCTRL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_SettingCTRL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_SettingCTRL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_SettingCTRL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_SettingCTRL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SettingCTRL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SettingCTRL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Advanced_Setting_Button = lv_btn_create(ui_controlSettingScreen);
lv_obj_set_width( ui_Advanced_Setting_Button, 105);
lv_obj_set_height( ui_Advanced_Setting_Button, 105);
lv_obj_set_x( ui_Advanced_Setting_Button, 180 );
lv_obj_set_y( ui_Advanced_Setting_Button, 0 );
lv_obj_set_align( ui_Advanced_Setting_Button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Advanced_Setting_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Advanced_Setting_Button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Advanced_Setting_Button, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Advanced_Setting_Button, lv_color_hex(0x080052), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Advanced_Setting_Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Advanced_Setting_Button, &ui_img_worker_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_width(ui_Advanced_Setting_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Advanced_Setting_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_Advanced_Setting_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_Advanced_Setting_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TurnOffCTRL = lv_btn_create(ui_controlSettingScreen);
lv_obj_set_width( ui_TurnOffCTRL, 105);
lv_obj_set_height( ui_TurnOffCTRL, 105);
lv_obj_set_x( ui_TurnOffCTRL, 60 );
lv_obj_set_y( ui_TurnOffCTRL, 0 );
lv_obj_set_align( ui_TurnOffCTRL, LV_ALIGN_CENTER );
lv_obj_add_state( ui_TurnOffCTRL, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_TurnOffCTRL, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_TurnOffCTRL, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_TurnOffCTRL, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TurnOffCTRL, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TurnOffCTRL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_TurnOffCTRL, &ui_img_68039786, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_width(ui_TurnOffCTRL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_TurnOffCTRL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_TurnOffCTRL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_TurnOffCTRL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_TurnOffCTRL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TurnOffCTRL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TurnOffCTRL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TurnOffCTRL, lv_color_hex(0x00BE10), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_TurnOffCTRL, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Status_info_Button = lv_btn_create(ui_controlSettingScreen);
lv_obj_set_width( ui_Status_info_Button, 105);
lv_obj_set_height( ui_Status_info_Button, 105);
lv_obj_set_x( ui_Status_info_Button, -60 );
lv_obj_set_y( ui_Status_info_Button, 0 );
lv_obj_set_align( ui_Status_info_Button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Status_info_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Status_info_Button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Status_info_Button, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Status_info_Button, lv_color_hex(0x080052), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Status_info_Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Status_info_Button, &ui_img_info_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_width(ui_Status_info_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Status_info_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_Status_info_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_Status_info_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_COOLER_IS__ON = lv_label_create(ui_controlSettingScreen);
lv_obj_set_width( ui_COOLER_IS__ON, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_COOLER_IS__ON, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_COOLER_IS__ON, 0 );
lv_obj_set_y( ui_COOLER_IS__ON, 180 );
lv_obj_set_align( ui_COOLER_IS__ON, LV_ALIGN_CENTER );
lv_label_set_text(ui_COOLER_IS__ON,"COOLER IS : ON");
lv_obj_add_flag( ui_COOLER_IS__ON, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_COOLER_IS__ON, lv_color_hex(0x00BE10), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_COOLER_IS__ON, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_COOLER_IS__ON, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_COOLER_IS__OFF = lv_label_create(ui_controlSettingScreen);
lv_obj_set_width( ui_COOLER_IS__OFF, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_COOLER_IS__OFF, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_COOLER_IS__OFF, 0 );
lv_obj_set_y( ui_COOLER_IS__OFF, 180 );
lv_obj_set_align( ui_COOLER_IS__OFF, LV_ALIGN_CENTER );
lv_label_set_text(ui_COOLER_IS__OFF,"COOLER IS : OFF");
lv_obj_add_flag( ui_COOLER_IS__OFF, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_COOLER_IS__OFF, lv_color_hex(0xFF0400), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_COOLER_IS__OFF, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_COOLER_IS__OFF, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_returnButton4, ui_event_returnButton4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SettingCTRL, ui_event_SettingCTRL, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Advanced_Setting_Button, ui_event_Advanced_Setting_Button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TurnOffCTRL, ui_event_TurnOffCTRL, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Status_info_Button, ui_event_Status_info_Button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_controlSettingScreen, ui_event_controlSettingScreen, LV_EVENT_ALL, NULL);
uic_controlSettingScreen = ui_controlSettingScreen;
uic_returnButton4 = ui_returnButton4;
uic_settingscreenlabel = ui_settingscreenlabel;
uic_SettingCTRL = ui_SettingCTRL;
uic_Advanced_Setting_Button = ui_Advanced_Setting_Button;
uic_TurnOffCTRL = ui_TurnOffCTRL;
uic_Status_info_Button = ui_Status_info_Button;
uic_COOLER_IS__ON = ui_COOLER_IS__ON;
uic_COOLER_IS__OFF = ui_COOLER_IS__OFF;

}

void ui_controlSettingScreen_screen_destroy(void)
{
   if (ui_controlSettingScreen) lv_obj_del(ui_controlSettingScreen);

// NULL screen variables
uic_controlSettingScreen= NULL;
ui_controlSettingScreen= NULL;
uic_returnButton4= NULL;
ui_returnButton4= NULL;
uic_settingscreenlabel= NULL;
ui_settingscreenlabel= NULL;
uic_SettingCTRL= NULL;
ui_SettingCTRL= NULL;
uic_Advanced_Setting_Button= NULL;
ui_Advanced_Setting_Button= NULL;
uic_TurnOffCTRL= NULL;
ui_TurnOffCTRL= NULL;
uic_Status_info_Button= NULL;
ui_Status_info_Button= NULL;
uic_COOLER_IS__ON= NULL;
ui_COOLER_IS__ON= NULL;
uic_COOLER_IS__OFF= NULL;
ui_COOLER_IS__OFF= NULL;

}
