// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainScreen
extern void ui_mainScreen_screen_init(void);
extern void ui_mainScreen_screen_destroy(void);
extern void ui_event_mainScreen( lv_event_t * e);
extern lv_obj_t *ui_mainScreen;
extern lv_obj_t *ui_Logo;
extern void ui_event_MenuButton( lv_event_t * e);
extern lv_obj_t *ui_MenuButton;
extern void ui_event_inlet_Arc( lv_event_t * e);
extern lv_obj_t *ui_inlet_Arc;
extern lv_obj_t *ui_inletMainsScreen;
extern void ui_event_outlet_Arc( lv_event_t * e);
extern lv_obj_t *ui_outlet_Arc;
extern lv_obj_t *ui_outletMainsScreen;
extern lv_obj_t *ui_Cooler_OFF_Icon;
extern lv_obj_t *ui_Cooler_ON_Icon;
extern lv_obj_t *ui_Compressor_ON_Icon;
extern lv_obj_t *ui_Compressor_OFF_Icon;
extern lv_obj_t *ui_High_Temp_Icon;
extern lv_obj_t *ui_Low_Temp_Icon;
extern lv_obj_t *ui_Low_Pressure_Icon;
extern lv_obj_t *ui_High_Pressure_Icon;
extern lv_obj_t *ui_Door_Open_Icon;
extern lv_obj_t *ui_Door_Close_Icon;
extern lv_obj_t *ui_arc_danger_outlet_;
extern lv_obj_t *ui_arc_danger_inlet;
// CUSTOM VARIABLES
extern lv_obj_t *uic_mainScreen;
extern lv_obj_t *uic_Logo;
extern lv_obj_t *uic_MenuButton;
extern lv_obj_t *uic_inlet_Arc;
extern lv_obj_t *uic_inletMainsScreen;
extern lv_obj_t *uic_outlet_Arc;
extern lv_obj_t *uic_outletMainsScreen;
extern lv_obj_t *uic_Cooler_OFF_Icon;
extern lv_obj_t *uic_Cooler_ON_Icon;
extern lv_obj_t *uic_Compressor_ON_Icon;
extern lv_obj_t *uic_Compressor_OFF_Icon;
extern lv_obj_t *uic_High_Temp_Icon;
extern lv_obj_t *uic_Low_Temp_Icon;
extern lv_obj_t *uic_Low_Pressure_Icon;
extern lv_obj_t *uic_High_Pressure_Icon;
extern lv_obj_t *uic_Door_Open_Icon;
extern lv_obj_t *uic_Door_Close_Icon;
extern lv_obj_t *uic_arc_danger_outlet_;
extern lv_obj_t *uic_arc_danger_inlet;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

