// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_STATUSSCREEN_H
#define UI_STATUSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_statusScreen
extern void ui_statusScreen_screen_init(void);
extern void ui_statusScreen_screen_destroy(void);
extern void ui_event_statusScreen( lv_event_t * e);
extern lv_obj_t *ui_statusScreen;
extern void ui_event_returnButton3( lv_event_t * e);
extern lv_obj_t *ui_returnButton3;
extern lv_obj_t *ui_statusscreenlabel;
extern lv_obj_t *ui_TEMP_Label;
extern lv_obj_t *ui_ALARM_Label;
extern lv_obj_t *ui_Status_Label;
extern lv_obj_t *ui_App_Connection_Label;
extern lv_obj_t *ui_info_Label;
extern lv_obj_t *ui_Maintenance_Label;
extern void ui_event_tempStatusButton( lv_event_t * e);
extern lv_obj_t *ui_tempStatusButton;
extern lv_obj_t *ui_tempStatusPanel;
extern void ui_event_returnButton11( lv_event_t * e);
extern lv_obj_t *ui_returnButton11;
extern lv_obj_t *ui_tempStatusLabel;
extern lv_obj_t *ui_inlet_temp_danger;
extern lv_obj_t *ui_outlet_temp_danger;
extern lv_obj_t *ui_antifreeze_temp_danger;
extern lv_obj_t *ui_filter_temp_danger;
extern lv_obj_t *ui_ContainerA1;
extern lv_obj_t *ui_Inlet_Temp_status;
extern lv_obj_t *ui_Outlet_Temp_status;
extern lv_obj_t *ui_antifreeze_temp_status;
extern lv_obj_t *ui_fan_2_filter_alarm_status;
extern void ui_event_alarmStatusButton( lv_event_t * e);
extern lv_obj_t *ui_alarmStatusButton;
extern lv_obj_t *ui_alarmStatusPanel;
extern void ui_event_returnButton2( lv_event_t * e);
extern lv_obj_t *ui_returnButton2;
extern lv_obj_t *ui_alarmStatusLabel;
extern lv_obj_t *ui_high_temp_danger;
extern lv_obj_t *ui_door_danger;
extern lv_obj_t *ui_filter_danger;
extern lv_obj_t *ui_high_pressure_danger;
extern lv_obj_t *ui_ContainerA2;
extern lv_obj_t *ui_high_Temp_Alarm;
extern lv_obj_t *ui_Door_Alarm;
extern lv_obj_t *ui_Filter_Alarm;
extern lv_obj_t *ui_high_Pressure_Alarm;
extern void ui_event_relayStatusButton( lv_event_t * e);
extern lv_obj_t *ui_relayStatusButton;
extern lv_obj_t *ui_relayStatusPanel;
extern void ui_event_returnButton7( lv_event_t * e);
extern lv_obj_t *ui_returnButton7;
extern lv_obj_t *ui_relayStatusLabel;
extern lv_obj_t *ui_ContainerA3;
extern lv_obj_t *ui_evaprartor_Fan_Status;
extern lv_obj_t *ui_Compressor_Status;
extern lv_obj_t *ui_condensor_Fan_1_Status;
extern lv_obj_t *ui_condensor_Fan_2_Status;
extern void ui_event_networkStatusButton( lv_event_t * e);
extern lv_obj_t *ui_networkStatusButton;
extern lv_obj_t *ui_networkStatusPanel;
extern void ui_event_returnButton8( lv_event_t * e);
extern lv_obj_t *ui_returnButton8;
extern lv_obj_t *ui_Connect_to_Device_Label;
extern lv_obj_t *ui_ContainerA4;
extern lv_obj_t *ui_access_Point_wifi;
extern lv_obj_t *ui_access_Point_Password;
extern lv_obj_t *ui_guidetext;
extern lv_obj_t *ui_QRcode_Tab;
extern lv_obj_t *ui_appldownload;
extern lv_obj_t *ui_Application_QR_Code;
extern lv_obj_t *ui_download_App_Label;
extern lv_obj_t *ui_connectToapp;
extern lv_obj_t *ui_Connection_QR_Code;
extern lv_obj_t *ui_Connect_App_Label;
extern void ui_event_show_QR_Code_Button( lv_event_t * e);
extern lv_obj_t *ui_show_QR_Code_Button;
extern void ui_event_Hide_QR_Code_Button( lv_event_t * e);
extern lv_obj_t *ui_Hide_QR_Code_Button;
extern void ui_event_deviceInfoButton( lv_event_t * e);
extern lv_obj_t *ui_deviceInfoButton;
extern lv_obj_t *ui_deviceInfoPanel;
extern void ui_event_returnButton9( lv_event_t * e);
extern lv_obj_t *ui_returnButton9;
extern lv_obj_t *ui_deviceInfoLabel;
extern lv_obj_t *ui_ContainerA5;
extern lv_obj_t *ui_serial_number;
extern lv_obj_t *ui_customerID;
extern lv_obj_t *ui_activationDate;
extern void ui_event_serviceInfoButton( lv_event_t * e);
extern lv_obj_t *ui_serviceInfoButton;
extern lv_obj_t *ui_serviceInfoPanel;
extern void ui_event_returnButton10( lv_event_t * e);
extern lv_obj_t *ui_returnButton10;
extern lv_obj_t *ui_serviceInfoLabel;
extern lv_obj_t *ui_ContainerA6;
extern lv_obj_t *ui_servicesintervals;
// CUSTOM VARIABLES
extern lv_obj_t *uic_statusScreen;
extern lv_obj_t *uic_returnButton3;
extern lv_obj_t *uic_statusscreenlabel;
extern lv_obj_t *uic_TEMP_Label;
extern lv_obj_t *uic_ALARM_Label;
extern lv_obj_t *uic_Status_Label;
extern lv_obj_t *uic_App_Connection_Label;
extern lv_obj_t *uic_info_Label;
extern lv_obj_t *uic_Maintenance_Label;
extern lv_obj_t *uic_tempStatusButton;
extern lv_obj_t *uic_tempStatusPanel;
extern lv_obj_t *uic_returnButton11;
extern lv_obj_t *uic_tempStatusLabel;
extern lv_obj_t *uic_inlet_temp_danger;
extern lv_obj_t *uic_outlet_temp_danger;
extern lv_obj_t *uic_antifreeze_temp_danger;
extern lv_obj_t *uic_filter_temp_danger;
extern lv_obj_t *uic_ContainerA1;
extern lv_obj_t *uic_Inlet_Temp_status;
extern lv_obj_t *uic_Outlet_Temp_status;
extern lv_obj_t *uic_antifreeze_temp_status;
extern lv_obj_t *uic_fan_2_filter_alarm_status;
extern lv_obj_t *uic_alarmStatusButton;
extern lv_obj_t *uic_alarmStatusPanel;
extern lv_obj_t *uic_returnButton2;
extern lv_obj_t *uic_alarmStatusLabel;
extern lv_obj_t *uic_high_temp_danger;
extern lv_obj_t *uic_door_danger;
extern lv_obj_t *uic_filter_danger;
extern lv_obj_t *uic_high_pressure_danger;
extern lv_obj_t *uic_ContainerA2;
extern lv_obj_t *uic_high_Temp_Alarm;
extern lv_obj_t *uic_Door_Alarm;
extern lv_obj_t *uic_Filter_Alarm;
extern lv_obj_t *uic_high_Pressure_Alarm;
extern lv_obj_t *uic_relayStatusButton;
extern lv_obj_t *uic_relayStatusPanel;
extern lv_obj_t *uic_returnButton7;
extern lv_obj_t *uic_relayStatusLabel;
extern lv_obj_t *uic_ContainerA3;
extern lv_obj_t *uic_evaprartor_Fan_Status;
extern lv_obj_t *uic_Compressor_Status;
extern lv_obj_t *uic_condensor_Fan_1_Status;
extern lv_obj_t *uic_condensor_Fan_2_Status;
extern lv_obj_t *uic_networkStatusButton;
extern lv_obj_t *uic_networkStatusPanel;
extern lv_obj_t *uic_returnButton8;
extern lv_obj_t *uic_Connect_to_Device_Label;
extern lv_obj_t *uic_ContainerA4;
extern lv_obj_t *uic_access_Point_wifi;
extern lv_obj_t *uic_access_Point_Password;
extern lv_obj_t *uic_guidetext;
extern lv_obj_t *uic_QRcode_Tab;
extern lv_obj_t *uic_Application_QR_Code;
extern lv_obj_t *uic_download_App_Label;
extern lv_obj_t *uic_connectToapp;
extern lv_obj_t *uic_Connection_QR_Code;
extern lv_obj_t *uic_Connect_App_Label;
extern lv_obj_t *uic_show_QR_Code_Button;
extern lv_obj_t *uic_Hide_QR_Code_Button;
extern lv_obj_t *uic_deviceInfoButton;
extern lv_obj_t *uic_deviceInfoPanel;
extern lv_obj_t *uic_returnButton9;
extern lv_obj_t *uic_deviceInfoLabel;
extern lv_obj_t *uic_ContainerA5;
extern lv_obj_t *uic_serial_number;
extern lv_obj_t *uic_customerID;
extern lv_obj_t *uic_activationDate;
extern lv_obj_t *uic_serviceInfoButton;
extern lv_obj_t *uic_serviceInfoPanel;
extern lv_obj_t *uic_returnButton10;
extern lv_obj_t *uic_serviceInfoLabel;
extern lv_obj_t *uic_ContainerA6;
extern lv_obj_t *uic_servicesintervals;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

