// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void bootScreen(lv_event_t * e)
{
	// Your code here
}

void settingScreen(lv_event_t * e)
{
	// Your code here
}

void turnOffCtrl_Checked(lv_event_t * e)
{
	// Your code here
}

void turnOffCtrl_Unchecked(lv_event_t * e)
{
	// Your code here
}

void processSettingScreen(lv_event_t * e)
{
	// Your code here
}

void submit_process_setting(lv_event_t * e)
{
	// Your code here
}

void addvancedSettingScreen(lv_event_t * e)
{
	// Your code here
}

void submit_advance_setting(lv_event_t * e)
{
	// Your code here
}

void TabView1AddvancedSetting(lv_event_t * e)
{
	// Your code here
}

void restart_device(lv_event_t * e)
{
	// Your code here
}

void reseting_sensors_address(lv_event_t * e)
{
	// Your code here
}

void sensors_disconnect_check(lv_event_t * e)
{
	// Your code here
}

void check_set_Inlet(lv_event_t * e)
{
	// Your code here
}

void check_set_Outlet(lv_event_t * e)
{
	// Your code here
}

void check_set_Antifreeze(lv_event_t * e)
{
	// Your code here
}

void check_set_Filter(lv_event_t * e)
{
	// Your code here
}

void goToFactoryReseting(lv_event_t * e)
{
	// Your code here
}

void satusScreen(lv_event_t * e)
{
	// Your code here
}

void show_QR_code(lv_event_t * e)
{
	// Your code here
}

void mainScreen(lv_event_t * e)
{
	// Your code here
}
